# Generated by Django 4.2.10 on 2025-07-01 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='image')),
                ('wall_image', models.ImageField(blank=True, help_text='Background image for category display', upload_to='categories/wall/', verbose_name='wall image')),
                ('cat_image', models.ImageField(blank=True, help_text='Icon or thumbnail for category', upload_to='categories/cat/', verbose_name='category image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='original price')),
                ('image', models.ImageField(upload_to='products/', verbose_name='main image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='best seller')),
                ('is_offer', models.BooleanField(default=False, verbose_name='on offer')),
                ('in_stock', models.BooleanField(default=True, verbose_name='in stock')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='weight (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='Format: LxWxH in cm', max_length=100, verbose_name='dimensions')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='warranty')),
                ('brand', models.CharField(default='RAFAL', max_length=100, verbose_name='brand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='color name')),
                ('hex_value', models.CharField(help_text='Format: #RRGGBB', max_length=7, verbose_name='hex color code')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this color variant', max_digits=10, verbose_name='price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='old price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'product color',
                'verbose_name_plural': 'product colors',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='feature')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'product feature',
                'verbose_name_plural': 'product features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('products', models.ManyToManyField(related_name='tags', to='products.product')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'product review',
                'verbose_name_plural': 'product reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
