# Generated by Django 4.2.10 on 2025-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FawryCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=255, verbose_name='reference number')),
                ('merchant_reference_number', models.CharField(max_length=255, verbose_name='merchant reference number')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='payment amount')),
                ('payment_method', models.CharField(max_length=50, verbose_name='payment method')),
                ('payment_status', models.CharField(max_length=20, verbose_name='payment status')),
                ('payment_date', models.DateTimeField(verbose_name='payment date')),
                ('raw_data', models.JSONField(verbose_name='raw data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fawry callback',
                'verbose_name_plural': 'Fawry callbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FawryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=255, unique=True, verbose_name='reference number')),
                ('merchant_reference_number', models.CharField(max_length=255, unique=True, verbose_name='merchant reference number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='UNPAID', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(default='PAYATFAWRY', max_length=50, verbose_name='payment method')),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
                ('customer_name', models.CharField(max_length=255, verbose_name='customer name')),
                ('customer_mobile', models.CharField(max_length=20, verbose_name='customer mobile')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('payment_code', models.CharField(blank=True, max_length=255, verbose_name='payment code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fawry payment',
                'verbose_name_plural': 'Fawry payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
