# Generated by Django 4.2.10 on 2025-07-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fawry_payment', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fawrypayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fawry_payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='fawrycallback',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='fawry_payment.fawrypayment'),
        ),
    ]
