# Generated by Django 4.2.10 on 2025-07-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymobPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymob_order_id', models.CharField(max_length=255, verbose_name='Paymob order ID')),
                ('payment_key', models.CharField(max_length=255, verbose_name='payment key')),
                ('integration_id', models.CharField(max_length=255, verbose_name='integration ID')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='amount in cents')),
                ('hmac', models.CharField(blank=True, max_length=255, verbose_name='HMAC')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('is_3d_secure', models.BooleanField(default=False, verbose_name='is 3D secure')),
                ('is_refunded', models.BooleanField(default=False, verbose_name='is refunded')),
                ('is_voided', models.BooleanField(default=False, verbose_name='is voided')),
                ('redirect_url', models.URLField(blank=True, verbose_name='redirect URL')),
                ('iframe_url', models.URLField(blank=True, verbose_name='iframe URL')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymob_payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paymob payment',
                'verbose_name_plural': 'Paymob payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymobCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='transaction ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='order ID')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='amount in cents')),
                ('success', models.BooleanField(verbose_name='success')),
                ('is_3d_secure', models.BooleanField(verbose_name='is 3D secure')),
                ('is_refunded', models.BooleanField(verbose_name='is refunded')),
                ('is_voided', models.BooleanField(verbose_name='is voided')),
                ('error_occured', models.BooleanField(verbose_name='error occurred')),
                ('has_parent_transaction', models.BooleanField(verbose_name='has parent transaction')),
                ('source_data_type', models.CharField(blank=True, max_length=50, verbose_name='source data type')),
                ('raw_data', models.JSONField(verbose_name='raw data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='paymob_payment.paymobpayment')),
            ],
            options={
                'verbose_name': 'Paymob callback',
                'verbose_name_plural': 'Paymob callbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
